spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/unitidepharma
spring.datasource.username=postgres
spring.datasource.password=Saurabhgiri699

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

cloudinary.cloud-name=dp4qv8lke
cloudinary.api-key=161951358638731
cloudinary.api-secret=EVvFCpHf-hmo69n_0i4Y7IyM1LQ

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
